[tool.poetry]
name = "kypython"
version = "0.1.0"
description = ""
authors = ["kyleadellinger <kyleadellinger@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.25.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
